[style]
; Colorscheme options listed here: https://github.com/lint069/ac-lua/blob/main/terminal-splashscreen/README.md
colorscheme = default

; Set colorscheme to "custom" to use your own colors.
; Format is RRGGBBAA
background = 000000FF
accent = 0000FFFF
text = FFFFFFFF
version_text = BEBEBEFF

[ascii]
; true|false
enabled = true
; Relative to this file
path = assets/example.txt
