[ABOUT]
NAME = kovaaks
AUTHOR = lint0, chris
VERSION = 0.9
REQUIRED_VERSION = 3748 ;0.3.0-preview211
URL = https://github.com/lint069

[CORE]
LAZY = FULL

[WINDOW_...]
ID = main
NAME = kovaaks
ICON = ./ico/icon.png
FUNCTION_MAIN = windowMain
;FUNCTION_ON_SHOW = init
SIZE = 300, 300
PADDING = 15, 10
FLAGS = MAIN, NO_SCROLLBAR

[WINDOW_1]
ID = settings
NAME = kovaaks settings
ICON = ./ico/icon.png
FUNCTION_MAIN = windowSettings
SIZE = 360, 400
PADDING = 15, 10
FLAGS = NO_SCROLLBAR
